### ISSUE TITLE
Why is the IDE for Rust not written in Rust? :)

### ISSUE THREAD

**Issue by D1mon** [krre/afterglow#1]

**Comment by krre** [comment]
In Rust no full-fledged gui-framework.

**Comment by D1mon** [comment]
https://areweguiyet.com/

**Comment by Inoshy** [comment]
> In Rust no full-fledged gui-framework.

you are the best this ide is so awesome love it!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
